PICK_COLOR = "Pick a Color! get a photo of the color you want!"
LOOKING_FOR = "This is The color you are looking For!"
ASK_NAME = "Hey, what is your name?"
WINNER_IS = "The Winner is "
YOUR_COLOR = " Your Color is "
COUNTDOWN = " seconds left!"
END_OF_GAME = "Thank you all for playing! bye bye!"